# Configuraci칩n de efectos
effects:
  # Jugadores
  playerCriticalHitParticles: totem_of_undying
  playerCriticalHitSound: entity.player.levelup
  playerMissParticles: angry_villager
  playerMissSound: entity.villager.no

  # Mobs
  mobCriticalHitParticles: smoke
  mobCriticalHitSound: entity.wither.spawn
  mobMissParticles: angry_villager
  mobMissSound: entity.villager.no

# Configuraci칩n de armas
weapons:
  woodensword:
    damageDice: 4  # d4
    bonus: 0
  goldensword:
    damageDice: 4  # d4
    bonus: 1
  stonesword:
    damageDice: 6  # d6
    bonus: 1
  ironsword:
    damageDice: 8  # d8
    bonus: 2
  diamondsword:
    damageDice: 10 # d10
    bonus: 3
  netheritesword:
    damageDice: 12 # d12
    bonus: 4
  bow:
    damageDice: 6  # d6
    bonus: 2
  crossbow:
    damageDice: 8  # d8
    bonus: 3
  trident:
    damageDice: 10 # d10
    bonus: 3
  default:
    damageDice: 2  # d2
    bonus: 0

# Configuraci칩n de da침o de mobs
mobs:
  zombieDamageDice: 4
  skeletonDamageDice: 6
  creeperDamageDice: 20
  wardenMeleeDamageDice: 30
  warden:
    sonicBoomChance: 0.5
  wardenSonicBoomDamage: 15
  spiderDamageDice: 4
  caveSpiderDamageDice: 4
  endermanDamageDice: 6
  blazeDamageDice: 8
  silverfishDamageDice: 2
  phantomDamageDice: 6
  piglinDamageDice: 6
  piglinBruteDamageDice: 12
  hoglinDamageDice: 8
  zoglinDamageDice: 10
  witherSkeletonDamageDice: 8
  evokerDamageDice: 8
  vindicatorDamageDice: 8
  ravagerDamageDice: 20
  ghastDamageDice: 10
  shulkerDamageDice: 4
  slimeSmallDamageDice: 2
  slimeMediumDamageDice: 4
  slimeLargeDamageDice: 6
  magmaCubeSmallDamageDice: 2
  magmaCubeMediumDamageDice: 4
  magmaCubeLargeDamageDice: 6
  defaultMobDamageDice: 2
